// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0fSbnGRw7leT_EWx1WlqObfcSNPxXK5c',
    appId: '1:839271889677:web:c936b5c6a56a0bb7688e44',
    messagingSenderId: '839271889677',
    projectId: 'masimu-215d8',
    authDomain: 'masimu-215d8.firebaseapp.com',
    storageBucket: 'masimu-215d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIqTpe3Z4q2ojRVv7dG9c4oKKgWFXJTrQ',
    appId: '1:839271889677:android:c66f561f754ecc86688e44',
    messagingSenderId: '839271889677',
    projectId: 'masimu-215d8',
    storageBucket: 'masimu-215d8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0fSbnGRw7leT_EWx1WlqObfcSNPxXK5c',
    appId: '1:839271889677:web:8380ca36b03e8f64688e44',
    messagingSenderId: '839271889677',
    projectId: 'masimu-215d8',
    authDomain: 'masimu-215d8.firebaseapp.com',
    storageBucket: 'masimu-215d8.appspot.com',
  );
}
